[package]
name = "protocol"
version = "0.1.0"
authors = ["Hanno Braun <hanno@braun-embedded.com>"]
edition = "2018"


[dependencies]
postcard = "*"

[dependencies.serde]
version          = "*"
default-features = false
